version: '3.9'
services:
  jsonify:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis:7.2
    container_name: cache
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  data:
  cache:


