version: '3.9'
services:
  jsonify:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./.env
